[package]
name = "rustml"
version = "0.0.2"
authors = ["Daniel Etzold <detzold@gmail.com>"]
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/daniel-e/rustml"
homepage = "http://daniel-e.github.io/rustml/rustml/"
documentation = "http://daniel-e.github.io/rustml/rustml/"
description = """
A library for doing maching learning in Rust.
"""

# Currently we can only upload up to 10MB. So we need to remove
# everything that is not required for building the library.
exclude = [
	"atlas/*",
	"build/*",
	"build_all.sh",
	"doc.sh",
	"examples/*",
	"datasets/*",
]

[lib]
name = "rustml"
path = "src/lib.rs"

[[example]]
name = "vector_addition"
path = "examples/vector_addition.rs"

[[example]]
name = "mnist_digits"
path = "examples/mnist_digits.rs"

[[example]]
name = "matrix_multiplication"
path = "examples/matrix_multiplication.rs"

[dependencies]
libc = "*"
rand = "*"
num = "*"
flate2 = "*"
time = "*"
